name: textless-clean
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch::pytorch>=1.13,<2.7
  - pytorch::torchaudio
  - pip
  - pip:
    - fairseq>=0.12.0
    - librosa>=0.9.0,<0.10.0
    - antlr4-python3-runtime==4.8
    - hydra-core>=1.1.0,<2.0.0
    - omegaconf>=2.1.0
    - pandas
    - numpy
